<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.0.16</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <NoWarn>1701;1702;CS0728;1587;1591</NoWarn>
    <PackageId>AventusSharp.Maui</PackageId>
    <Title>AventusSharp MAUI</Title>
    <Description>In-process MAUI bridge for AventusSharp.</Description>
    <Authors>Cobwebsite</Authors>
    <Company>ch.cobwebsite</Company>
    <RepositoryUrl>https://github.com/Cobwebsite/AventusSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>logo_sharp.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\logo_sharp.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AventusSharp.Core\AventusSharp.Core.csproj" />
    <PackageReference Include="Microsoft.Maui.Core" Version="10.0.20" />
  </ItemGroup>

</Project>
