<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PackageId>AventusSharp.Converter</PackageId>
    <Version>0.0.19</Version>
    <Authors>Cobwebsite</Authors>
    <Company>ch.cobwebsite</Company>
    <Copyright>Copyright © 2024 Cobwebsite</Copyright>
    <Description>Convert AventusSharp code to Typescript or AventusJs.</Description>
    <PackageTags>csharp typescript converter dotnet-tool</PackageTags>
    <RepositoryUrl>https://github.com/Cobwebsite/AventusSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/Cobwebsite/AventusSharp</PackageProjectUrl>
    <PackageIcon>logo_sharp.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>

    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <IsPackable>true</IsPackable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>csharp-converter</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
    <PackageReference Include="Google.Protobuf" Version="3.33.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../logo_sharp.png" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="../LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AventusSharp.AspNetCore\AventusSharp.AspNetCore.csproj" />
  </ItemGroup>

</Project>
