using AventusSharp.Data;
using AventusSharp.Data.Attributes;
using AventusSharp.Data.Manager;
using AventusSharp.Data.Manager.DB.Builders;
using AventusSharp.Data.Storage.Default;
using AventusSharpTest.Integration.Containers;
using AventusSharpTest.Integration.Models;
using NUnit.Framework;

namespace AventusSharpTest.Integration;

[TestFixture]
[NonParallelizable]
public sealed class BulkCreateProviderTests
{
    private static IDBStorage Storage(string kind)
    {
        DatabaseContainers.RequireDocker();
        return kind switch
        {
            "MySQL" => DatabaseContainers.MySql,
            "PostgreSQL" => DatabaseContainers.PostgreSql,
            _ => DatabaseContainers.MsSql
        };
    }

    private static string Identity(string kind) => kind switch
    {
        "MySQL" => "int AUTO_INCREMENT PRIMARY KEY",
        "PostgreSQL" => "int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "int IDENTITY(1, 1) PRIMARY KEY"
    };

    private static async Task Execute(IDBStorage storage, string sql)
    {
        var result = await storage.Execute(sql);
        Assert.That(result.Success, Is.True, IntegrationEnvironment.ErrorMessages(result.Errors));
    }

    private static async Task<int> Count(IDBStorage storage, string table)
    {
        var rows = await storage.Query($"SELECT COUNT(*) AS count FROM {storage.QuoteIdentifier(table)}");
        Assert.That(rows.Success, Is.True, IntegrationEnvironment.ErrorMessages(rows.Errors));
        return int.Parse(rows.Result!.Single()["count"]!);
    }

    private static async Task<IDBStorage> PrepareLinks(string kind, Type? ownerType = null)
    {
        var storage = Storage(kind);
        ownerType ??= typeof(BulkLinkOwner);
        var registered = storage.AddPyramid(new(typeof(Storable<>).MakeGenericType(ownerType), new())
        {
            isForceInherit = true,
            children = [new(ownerType, new())]
        });
        Assert.That(registered.Success, Is.True, IntegrationEnvironment.ErrorMessages(registered.Errors));
        string Q(string name) => storage.QuoteIdentifier(name);
        foreach (string table in new[] { "bulk_link_owners_bulk_link_tags", "bulk_link_owners", "bulk_link_tags" })
            await Execute(storage, $"DROP TABLE IF EXISTS {Q(table)}");
        await Execute(storage, $"CREATE TABLE {Q("bulk_link_tags")} ({Q("Id")} int PRIMARY KEY)");
        await Execute(storage, $"INSERT INTO {Q("bulk_link_tags")} VALUES (1), (2)");
        await Execute(storage, $"CREATE TABLE {Q("bulk_link_owners")} ({Q("Id")} {Identity(kind)}, "
            + $"{Q("Name")} varchar(100) NOT NULL, {Q("A")} int, {Q("B")} int, {Q("C")} int, {Q("D")} int)");
        await Execute(storage, $"CREATE TABLE {Q("bulk_link_owners_bulk_link_tags")} "
            + $"({Q("bulk_link_owners_Id")} int, {Q("bulk_link_tags_Id")} int, "
            + $"PRIMARY KEY ({Q("bulk_link_owners_Id")}, {Q("bulk_link_tags_Id")}), "
            + $"FOREIGN KEY ({Q("bulk_link_owners_Id")}) REFERENCES {Q("bulk_link_owners")} ({Q("Id")}), "
            + $"FOREIGN KEY ({Q("bulk_link_tags_Id")}) REFERENCES {Q("bulk_link_tags")} ({Q("Id")}))");
        return storage;
    }

    [Test]
    public async Task Requested_batch_size_is_capped_by_sql_server_parameter_limit()
    {
        var storage = await PrepareLinks("SQLServer");
        var values = Enumerable.Range(0, 700).Select(index => new BulkLinkOwner
        {
            Id = 60_000 + index, Name = "Capped " + index
        }).ToList();
        var builder = new DatabaseCreateBuilder<BulkLinkOwner>(storage, GenericDM.Get<Device>());

        var result = await builder.RunBulkWithError(values,
            new BulkCreateOptions { WithId = true, BatchSize = 700 });

        Assert.That(result.Success, Is.True, IntegrationEnvironment.ErrorMessages(result.Errors));
        Assert.That(await Count(storage, "bulk_link_owners"), Is.EqualTo(values.Count));
    }

    [TestCase("MySQL")]
    [TestCase("PostgreSQL")]
    [TestCase("SQLServer")]
    public async Task Dictionary_links_and_reused_builder_preserve_generated_ids(string kind)
    {
        var storage = await PrepareLinks(kind, typeof(BulkDictionaryOwner));
        var builder = new DatabaseCreateBuilder<BulkDictionaryOwner>(storage, GenericDM.Get<Device>());
        BulkDictionaryOwner NewOwner(int id) => new()
        {
            Id = id, Name = "Dictionary owner",
            Tags = new()
            {
                [1] = new BulkLinkTag { Id = 1 },
                [2] = new BulkLinkTag { Id = 1 },
                [3] = new BulkLinkTag { Id = 2 }
            }
        };
        var explicitOwner = NewOwner(40_000);
        var explicitResult = await builder.RunBulkWithError([explicitOwner], new BulkCreateOptions { WithId = true });
        Assert.That(explicitResult.Success, Is.True, IntegrationEnvironment.ErrorMessages(explicitResult.Errors));
        var generatedOwner = NewOwner(0);
        var generatedResult = await builder.RunBulkWithError([generatedOwner], new BulkCreateOptions { WithId = false });
        Assert.That(generatedResult.Success, Is.True, IntegrationEnvironment.ErrorMessages(generatedResult.Errors));
        Assert.That(generatedOwner.Id, Is.Positive.And.Not.EqualTo(explicitOwner.Id));
        Assert.That(await Count(storage, "bulk_link_owners"), Is.EqualTo(2));
        Assert.That(await Count(storage, "bulk_link_owners_bulk_link_tags"), Is.EqualTo(4));
    }

    [TestCase("MySQL", true)]
    [TestCase("PostgreSQL", true)]
    [TestCase("SQLServer", true)]
    [TestCase("MySQL", false)]
    [TestCase("PostgreSQL", false)]
    [TestCase("SQLServer", false)]
    public async Task Bulk_links_preserve_owner_identifiers_and_deduplicate_links(string kind, bool withId)
    {
        var storage = await PrepareLinks(kind);
        int count = withId ? 501 : 3;
        var values = Enumerable.Range(0, count).Select(index => new BulkLinkOwner
        {
            Id = withId ? 10_000 + index : 0, Name = "Owner " + index, Tags = [1, 1, 2]
        }).ToList();
        values[0].Tags = [];
        var builder = new DatabaseCreateBuilder<BulkLinkOwner>(storage, GenericDM.Get<Device>());
        var result = await builder.RunBulkWithError(values, new BulkCreateOptions { WithId = withId });
        Assert.That(result.Success, Is.True, IntegrationEnvironment.ErrorMessages(result.Errors));
        Assert.That(await Count(storage, "bulk_link_owners"), Is.EqualTo(count));
        Assert.That(await Count(storage, "bulk_link_owners_bulk_link_tags"), Is.EqualTo((count - 1) * 2));
        Assert.That(values.All(value => value.Id > 0), Is.True);
    }

    [TestCase("MySQL", true)]
    [TestCase("PostgreSQL", true)]
    [TestCase("SQLServer", true)]
    [TestCase("MySQL", false)]
    [TestCase("PostgreSQL", false)]
    [TestCase("SQLServer", false)]
    public async Task Invalid_link_rolls_back_all_owner_and_link_rows(string kind, bool withId)
    {
        var storage = await PrepareLinks(kind);
        int count = withId ? 501 : 3;
        var values = Enumerable.Range(0, count).Select(index => new BulkLinkOwner
        {
            Id = withId ? 20_000 + index : 0, Name = "Owner " + index, Tags = [1]
        }).ToList();
        values[^1].Tags = [999_999];
        var builder = new DatabaseCreateBuilder<BulkLinkOwner>(storage, GenericDM.Get<Device>());
        var result = await builder.RunBulkWithError(values, new BulkCreateOptions { WithId = withId });
        Assert.That(result.Success, Is.False);
        Assert.That(await Count(storage, "bulk_link_owners"), Is.Zero);
        Assert.That(await Count(storage, "bulk_link_owners_bulk_link_tags"), Is.Zero);
        if (!withId) Assert.That(values.All(value => value.Id == 0), Is.True);
    }

    [TestCase("MySQL", true)]
    [TestCase("PostgreSQL", true)]
    [TestCase("SQLServer", true)]
    [TestCase("MySQL", false)]
    [TestCase("PostgreSQL", false)]
    [TestCase("SQLServer", false)]
    public async Task Mixed_inherited_types_share_parent_identifiers(string kind, bool withId)
    {
        var storage = Storage(kind);
        Type parentType = IntegrationEnvironment.Storage.GetTableInfo(typeof(TestDimmer))!.Parent!.Type;
        var pyramid = new PyramidInfo(parentType, new())
        {
            aliasType = typeof(ITestActuator),
            children = [new(typeof(TestDimmer), new()), new(typeof(TestRelay), new())]
        };
        var registered = storage.AddPyramid(new(typeof(Storable<ITestActuator>), new())
        {
            isForceInherit = true,
            children = [pyramid]
        });
        Assert.That(registered.Success, Is.True, IntegrationEnvironment.ErrorMessages(registered.Errors));
        string Q(string name) => storage.QuoteIdentifier(name);
        foreach (string table in new[] { "test_advanced_dimmers", "test_advanced_actuators", "test_dimmers", "test_relays", "test_actuators" })
            await Execute(storage, $"DROP TABLE IF EXISTS {Q(table)}");
        await Execute(storage, $"CREATE TABLE {Q("test_actuators")} ({Q("Id")} {Identity(kind)}, "
            + $"{Q("Name")} varchar(100) NOT NULL, {Q("__type")} varchar(1000) NOT NULL)");
        await Execute(storage, $"CREATE TABLE {Q("test_dimmers")} ({Q("Id")} int PRIMARY KEY, {Q("Level")} int, "
            + $"FOREIGN KEY ({Q("Id")}) REFERENCES {Q("test_actuators")} ({Q("Id")}))");
        string booleanType = kind == "PostgreSQL" ? "boolean" : "bit";
        await Execute(storage, $"CREATE TABLE {Q("test_relays")} ({Q("Id")} int PRIMARY KEY, {Q("IsClosed")} {booleanType}, "
            + $"FOREIGN KEY ({Q("Id")}) REFERENCES {Q("test_actuators")} ({Q("Id")}))");
        List<ITestActuator> values = [];
        int count = withId ? 502 : 4;
        for (int index = 0; index < count; index++)
        {
            int id = withId ? 30_000 + index : 0;
            if (index % 2 == 0) values.Add(new TestDimmer { Id = id, Name = "Dimmer " + index, Level = index });
            else values.Add(new TestRelay { Id = id, Name = "Relay " + index, IsClosed = true });
        }
        var builder = new DatabaseCreateBuilder<ITestActuator>(storage, GenericDM.Get<ITestActuator>(), typeof(TestDimmer));
        var result = await builder.RunBulkWithError(values, new BulkCreateOptions { WithId = withId });
        Assert.That(result.Success, Is.True, IntegrationEnvironment.ErrorMessages(result.Errors));
        Assert.That(await Count(storage, "test_actuators"), Is.EqualTo(count));
        Assert.That(await Count(storage, "test_dimmers"), Is.EqualTo(count / 2));
        Assert.That(await Count(storage, "test_relays"), Is.EqualTo(count / 2));
        var parents = await storage.Query($"SELECT {Q("Id")} FROM {Q("test_actuators")}");
        Assert.That(parents.Success, Is.True, IntegrationEnvironment.ErrorMessages(parents.Errors));
        Assert.That(parents.Result!.Select(row => int.Parse(row["Id"]!)), Is.EquivalentTo(values.Select(value => value.Id)));
    }

    [TestCase("MySQL")]
    [TestCase("PostgreSQL")]
    [TestCase("SQLServer")]
    public async Task Deleting_three_level_inheritance_removes_each_table_and_preserves_other_rows(string kind)
    {
        var storage = Storage(kind);
        var rootType = IntegrationEnvironment.Storage.GetTableInfo(typeof(TestAdvancedDimmer))!.Parent!.Parent!.Type;
        var middleType = IntegrationEnvironment.Storage.GetTableInfo(typeof(TestAdvancedDimmer))!.Parent!.Type;
        var registered = storage.AddPyramid(new(typeof(Storable<ITestActuator>), new())
        {
            isForceInherit = true,
            children = [new(rootType, new())
            {
                aliasType = typeof(ITestActuator),
                children = [new(middleType, new())
                {
                    aliasType = typeof(ITestAdvancedActuator),
                    children = [new(typeof(TestAdvancedDimmer), new())]
                }]
            }]
        });
        Assert.That(registered.Success, Is.True, IntegrationEnvironment.ErrorMessages(registered.Errors));
        string Q(string name) => storage.QuoteIdentifier(name);
        foreach (string table in new[] { "test_advanced_dimmers", "test_advanced_actuators", "test_dimmers", "test_relays", "test_actuators" })
            await Execute(storage, $"DROP TABLE IF EXISTS {Q(table)}");
        await Execute(storage, $"CREATE TABLE {Q("test_actuators")} ({Q("Id")} int PRIMARY KEY, {Q("Name")} varchar(100), {Q("__type")} varchar(1000))");
        await Execute(storage, $"CREATE TABLE {Q("test_advanced_actuators")} ({Q("Id")} int PRIMARY KEY, {Q("Category")} varchar(100), FOREIGN KEY ({Q("Id")}) REFERENCES {Q("test_actuators")} ({Q("Id")}))");
        await Execute(storage, $"CREATE TABLE {Q("test_advanced_dimmers")} ({Q("Id")} int PRIMARY KEY, {Q("Brightness")} int, FOREIGN KEY ({Q("Id")}) REFERENCES {Q("test_advanced_actuators")} ({Q("Id")}))");
        foreach (int id in new[] { 1, 2 })
        {
            await Execute(storage, $"INSERT INTO {Q("test_actuators")} VALUES ({id}, 'name{id}', '{typeof(TestAdvancedDimmer).AssemblyQualifiedName!.Replace("'", "''")}')");
            await Execute(storage, $"INSERT INTO {Q("test_advanced_actuators")} VALUES ({id}, 'category{id}')");
            await Execute(storage, $"INSERT INTO {Q("test_advanced_dimmers")} VALUES ({id}, {id * 10})");
        }
        var manager = GenericDM.Get<ITestActuator>();
        var deleted = await new DatabaseDeleteBuilder<ITestActuator>(storage, manager, false, typeof(TestAdvancedDimmer))
            .Where(item => item.Name == "name1").RunWithError();
        Assert.That(deleted.Success, Is.True, IntegrationEnvironment.ErrorMessages(deleted.Errors));
        foreach (string table in new[] { "test_actuators", "test_advanced_actuators", "test_advanced_dimmers" })
        {
            var rows = await storage.Query($"SELECT {Q("Id")} FROM {Q(table)}");
            Assert.That(rows.Result!.Select(row => row["Id"]), Is.EqualTo(new[] { "2" }), table);
        }
    }
}

[ManualInit]
[SqlName("bulk_link_owners")]
public sealed class BulkLinkOwner : Storable<BulkLinkOwner>
{
    public string Name { get; set; } = "";
    public int A { get; set; }
    public int B { get; set; }
    public int C { get; set; }
    public int D { get; set; }
    [ForeignKey<BulkLinkTag>]
    public List<int> Tags { get; set; } = [];
}

[SqlName("bulk_link_tags")]
public sealed class BulkLinkTag : Storable<BulkLinkTag> { }

[ManualInit]
[SqlName("bulk_link_owners")]
public sealed class BulkDictionaryOwner : Storable<BulkDictionaryOwner>
{
    public string Name { get; set; } = "";
    public Dictionary<int, BulkLinkTag> Tags { get; set; } = [];
}
