<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.0.18</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <NoWarn>1701;1702;CS0728;1587;1591</NoWarn>
    <PackageId>AventusSharp.AspNetCore</PackageId>
    <Title>AventusSharp ASP.NET Core</Title>
    <Description>ASP.NET Core hosting adapter for AventusSharp.</Description>
    <Authors>Cobwebsite</Authors>
    <Company>ch.cobwebsite</Company>
    <RepositoryUrl>https://github.com/Cobwebsite/AventusSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>logo_sharp.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RootNamespace>AventusSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\logo_sharp.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\AventusSharp.Core\AventusSharp.Core.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Scriban" Version="7.2.5" />
  </ItemGroup>

</Project>
